### ISSUE TITLE
wifi cannot be loaded

### ISSUE THREAD

**Issue by york-cmd** [adrianjagielak/lenovo_y520_efi#1]
Hello, I would like to ask if you encounter a situation where the wifi driver can search for wifi, but the network card cannot be loaded

**Comment by adrianjagielak** [comment]
Check if you have Intel wifi card (some of Lenovo Legion Y520 have Atheros) and when you are sure that you have Intel try the latest build of itlwm.kext and HeliPort.app from [here](https://github.com/1hbb/OpenIntelWireless-Factory/releases)
