### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by ravenll** [adrianjagielak/lenovo_y520_efi#12]
I updated to 11.2.3 and the bluetooth is no more working...

**Comment by adrianjagielak** [comment]
My Y520 is no longer alive, but try adding the [IntelBluetooth](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases/tag/1.1.2) kext to your kexts folders and your config.plist. If it will solve the issue I will add this to my repo so please let me know:)

**Comment by ravenll** [comment]
Thank you, now is everyting working... 

And i also deleted codecommander.. because it has confict with aplealc.. and the sound was not always working

**Comment by adrianjagielak** [comment]
Thanks, updated my EFI :)

https://github.com/adrianjagielak/lenovo_y520_efi/releases/tag/11.2.3
