### ISSUE TITLE
is bluetooth work?

### ISSUE THREAD

**Issue by amrelgendy0** [adrianjagielak/lenovo_y520_efi#2]

**Comment by adrianjagielak** [comment]
In Catalina I had some troubles with some devices, other worked great. In Big Sur I only tested AirPods Pro and Apple Magic Trackpad 2 that I use in work and they work perfect

**Comment by amrelgendy0** [comment]
with me bluetooth was work fine on catalina but in big sur not work

and i have another issue sound works in some times and some times not and i had to restart many time to work!!
do you have a solution about that ?

**Comment by adrianjagielak** [comment]
What EFI did you use?

**Comment by amrelgendy0** [comment]
i make my efi and today i used yours and both have the same problem

**Comment by adrianjagielak** [comment]
Weird.
What exactly is you laptop model? (And if i5/i7, gtx1050/1060 etc)

**Comment by amrelgendy0** [comment]
Legion Y520-15IKBN Laptop (Lenovo) - Type 80WK
i5 7300hq
gtx 1050

**Comment by adrianjagielak** [comment]
Try adding `alcdelay=1000` in boot-args or change alcid to some other layout id for example `alcid=20`

**Comment by amrelgendy0** [comment]
works at alcid=14 thanks

**Comment by Asdrubal-Lavin** [comment]
> trabaja en alcid = 14 gracias

You could share your EFI for Lenovo legion Y520 i5 7300hq gtx 1050ti?

**Comment by adrianjagielak** [comment]
> You could share your EFI for Lenovo legion Y520 i5 7300hq gtx 1050ti?

Did you tried with this repo?

**Comment by Asdrubal-Lavin** [comment]
> > ¿Puede compartir su EFI para Lenovo legion Y520 i5 7300hq gtx 1050ti?
> 
> ¿Intentaste con este repositorio?

No , i Will try in this moment whit this repository, thanks

**Comment by adrianjagielak** [comment]
No problem, im glad people are using my EFI :)
