### ISSUE TITLE
有没有big sur11.1的安装包 链接可以分享一下吗

### ISSUE THREAD

**Issue by IM515BT** [adrianjagielak/lenovo_y520_efi#5]
有没有big sur11.1的安装包 链接可以分享一下吗

**Comment by adrianjagielak** [comment]
Hi! Sorry for the late reply and thank you for your interest in my EFI!
Unfortunately, I don't speak Chinese but if Google Translate worked ("Is there a big sur11.1 installation package? Can you share the link?") I understand that you want to install Big Sur 11.1

This EFI is 100% compatible with Big Sur 11.1 on Lenovo Legion Y520 and you can download it via this GitHub Release: [11.1.zip](https://github.com/adrianjagielak/lenovo_y520_efi/archive/11.1.zip)

**Comment by IM515BT** [comment]
thanks your EFI ,i got install big sur 11.1 package.

**Comment by adrianjagielak** [comment]
I'm glad I could help :)
