### ISSUE TITLE
About airdrop with Intel Wi-Fi Drivers for macOS 

### ISSUE THREAD

**Issue by mehmetyukcell** [adrianjagielak/lenovo_y520_efi#9]
Airdrop works in the your system with airportitlwm?

**Comment by adrianjagielak** [comment]
"Currently, only Handoff and Universal Clipboard works with AirportItlwm, other features are not supported":

https://openintelwireless.github.io/itlwm/FAQ.html#does-it-support-apple-s-continuity-framework-airdrop-handoff
